---

emulators:
  - id: gba
    name: GameBoy Advance
    icon:
      filename: "assets/gameboy.png"
      x: 7
      y: 4
    exec: "vba {rom}"
    roms: "/home/nathanpc/ROMs/GameBoy/"
    ignore_ext: ".sav"
  - id: genesis
    name: Sega Genesis
    icon:
      filename: "assets/psone.png"
      x: 8
      y: 25
    exec: "dgen {rom}"
    roms: "/home/nathanpc/ROMs/Genesis/"

...
